version: "3"
services:
  hadoop-master:
    image: hadoop-toy:1.0
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: hadoop-master
    tty: true
    ports:
      - 9870:9870
      - 8088:8088
      - 19888:19888
    volumes:
      - ./data:/root/data
    networks:
      - hadoop

  hadoop-slave1:
    image: hadoop-toy:1.0
    container_name: hadoop-slave1
    tty: true
    depends_on:
      - hadoop-master
    networks:
      - hadoop

  hadoop-slave2:
    image: hadoop-toy:1.0
    container_name: hadoop-slave2
    tty: true
    depends_on:
      - hadoop-master
    networks:
      - hadoop
      
  # add slave-* here!
  
networks:
  hadoop:
    driver: bridge